export enum SocialFeedEvent {
    // 点击评论 弹出删除 copy按钮
    ON_SHOW_COMMENT_OPT_VIEW = "FEED_ON_SHOW_COMMENT_OPT_VIEW",
    // 发布帖子
    ON_SHOW_SUBMIT_POST_VIEW = "FEED_ON_SHOW_SUBMIT_POST_VIEW",
    // ON_SHOW_FEED_SUBMIT_POST_VIEW = "ON_SHOW_FEED__POST_VIEW"
    // 发表评论
    ON_SHOW_SUBMIT_COMMENT_VIEW = "FEED_ON_SHOW_SUBMIT_COMMENT_VIEW",
    ON_SHOW_NOTICE_VIEW = "ON_SHOW_NOTICE_VIEW"
}


export enum SocialContactsEvent {
    // 点击评论 弹出删除 copy按钮
    ON_SHOW_CONTACTS_NEW_FRIEND = "CONTACTS_ON_SHOW_CONTACTS_NEW_FRIEND",
    // 发布帖子
    ON_SHOW_CONTACTS_BLACKLIST = "CONTACTS_ON_SHOW_CONTACTS_BLACKLIST",
    // ON_SHOW_FEED_SUBMIT_POST_VIEW = "ON_SHOW_FEED__POST_VIEW"

}


export enum SocialChatSettingEvent {
    ON_GROUP_INFO_CHANGE = "SETTING_ON_GROUP_INFO_CHANGE"
}
