



enum Meta {
    _1_Audio_Chat_String1 = "man/Audio_Chat_String1",
    _1_Audio_Chat_String10 = "man/Audio_Chat_String10",
    _1_Audio_Chat_String2 = "man/Audio_Chat_String2",
    _1_Audio_Chat_String3 = "man/Audio_Chat_String3",
    _1_Audio_Chat_String4 = "man/Audio_Chat_String4",
    _1_Audio_Chat_String5 = "man/Audio_Chat_String5",
    _1_Audio_Chat_String6 = "man/Audio_Chat_String6",
    _1_Audio_Chat_String7 = "man/Audio_Chat_String7",
    _1_Audio_Chat_String8 = "man/Audio_Chat_String8",
    _1_Audio_Chat_String9 = "man/Audio_Chat_String9",
    _1_buyao = "man/buyao",
    _1_jiaofen0 = "man/jiaofen0",
    _1_jiaofen1 = "man/jiaofen1",
    _1_jiaofen2 = "man/jiaofen2",
    _1_jiaofen3 = "man/jiaofen3",
    
    _1_opcode0 = "man/CallLandlord_BJDZ",
    _1_opcode1 = "man/CallLandlord_JDZ",
    _1_opcode2 = "man/CallLandlord_QDZ",
    _1_opcode3 = "man/CALL_DOUBLE",
    _1_opcode4 = "man/chaojijiabei",
    _1_opcode5 = "man/CallLandlord_BQDZ",
    _1_opcode6 = "man/CALL_NO_DOUBLE",
  
    _1_Audio_Pass1 = "man/Audio_Pass1",
    _1_Audio_Pass2 = "man/Audio_Pass2",
    _1_Audio_Pass3 = "man/Audio_Pass3",
    _1_Audio_Spring = "man/Audio_Spring",
    _1_Audio_Pressing1 = "man/Audio_Pressing1",
    _1_Audio_Pressing2 = "man/Audio_Pressing2",
    _1_Audio_Pressing3 = "man/Audio_Pressing3",
    _1_pattern_dan14 = "man/pattern_dan14",
    _1_pattern_dan10 = "man/pattern_dan10",
    _1_pattern_dan11 = "man/pattern_dan11",
    _1_pattern_dan12 = "man/pattern_dan12",
    _1_pattern_dan13 = "man/pattern_dan13",
    _1_pattern_dan16 = "man/pattern_dan16",
    _1_pattern_dan17 = "man/pattern_dan17",
    _1_pattern_dan15 = "man/pattern_dan15",
    _1_pattern_dan3 = "man/pattern_dan3",
    _1_pattern_dan4 = "man/pattern_dan4",
    _1_pattern_dan5 = "man/pattern_dan5",
    _1_pattern_dan6 = "man/pattern_dan6",
    _1_pattern_dan7 = "man/pattern_dan7",
    _1_pattern_dan8 = "man/pattern_dan8",
    _1_pattern_dan9 = "man/pattern_dan9",
    _1_pattern_dui14 = "man/pattern_dui14",
    _1_pattern_dui10 = "man/pattern_dui10",
    _1_pattern_dui11 = "man/pattern_dui11",
    _1_pattern_dui12 = "man/pattern_dui12",
    _1_pattern_dui13 = "man/pattern_dui13",
    _1_pattern_dui16 = "man/pattern_dui16",
    _1_pattern_dui17 = "man/pattern_dui17",
    _1_pattern_dui15 = "man/pattern_dui15",
    _1_pattern_dui3 = "man/pattern_dui3",
    _1_pattern_dui4 = "man/pattern_dui4",
    _1_pattern_dui5 = "man/pattern_dui5",
    _1_pattern_dui6 = "man/pattern_dui6",
    _1_pattern_dui7 = "man/pattern_dui7",
    _1_pattern_dui8 = "man/pattern_dui8",
    _1_pattern_dui9 = "man/pattern_dui9",
    _1_remain1 = 	"man/remain1",
	_1_remain2 = 	"man/remain2",
	_1_pattern3 = 	"man/pattern3",
	_1_pattern4 = 	"man/pattern4",
	_1_pattern5 = 	"man/pattern5",
	_1_pattern6 = 	"man/pattern6",
	_1_pattern7 = 	"man/pattern7",
	_1_pattern8 = 	"man/pattern8",
	_1_pattern9 = 	"man/pattern9",
	_1_pattern10 = 	"man/pattern10",
	_1_pattern11 = 	"man/pattern11",
	_1_pattern12 = 	"man/pattern12",
	_1_pattern13 = 	"man/pattern13",
	_1_pattern14 = 	"man/pattern11",
	_1_pattern15 = 	"man/pattern11",
	_1_pattern17 = 	"man/pattern17",
	_1_pattern18 = 	"man/pattern18",
	_1_pattern19 = 	"man/pattern19",


	_2_Audio_Chat_String1 = 	"woman/Audio_Chat_String1",
	_2_Audio_Chat_String10 = 	"woman/Audio_Chat_String10",
	_2_Audio_Chat_String2 = 	"woman/Audio_Chat_String2",
	_2_Audio_Chat_String3 = 	"woman/Audio_Chat_String3",
	_2_Audio_Chat_String4 = 	"woman/Audio_Chat_String4",
	_2_Audio_Chat_String5 = 	"woman/Audio_Chat_String5",
	_2_Audio_Chat_String6 = 	"woman/Audio_Chat_String6",
	_2_Audio_Chat_String7 = 	"woman/Audio_Chat_String7",
	_2_Audio_Chat_String8 = 	"woman/Audio_Chat_String8",
	_2_Audio_Chat_String9 = 	"woman/Audio_Chat_String9",
	_2_buyao = 		"woman/buyao",
	_2_jiaofen0 = 	"woman/jiaofen0",
	_2_jiaofen1 = 	"woman/jiaofen1",
	_2_jiaofen2 = 	"woman/jiaofen2",
	_2_jiaofen3 = 	"woman/jiaofen3",

	_2_opcode0 = 	"woman/CallLandlord_BJDZ",
	_2_opcode1 = 	"woman/CallLandlord_JDZ",
	_2_opcode2 = 	"woman/CallLandlord_QDZ",
	_2_opcode3 = 	"woman/CALL_DOUBLE",
	_2_opcode4 = 	"woman/chaojijiabei",
	_2_opcode5 = 	"woman/CallLandlord_BQDZ",
	_2_opcode6 = 	"woman/CALL_NO_DOUBLE",


	_2_Audio_Pass1 = 	"woman/Audio_Pass1",
	_2_Audio_Pass2 = 	"woman/Audio_Pass2",
	_2_Audio_Pass3 = 	"woman/Audio_Pass3",
	_2_Audio_Spring = 	"woman/Audio_Spring",
	_2_Audio_Pressing1 = 	"woman/Audio_Yasi1",
	_2_Audio_Pressing2 = 	"woman/Audio_Yasi2",
	_2_Audio_Pressing3 = 	"woman/Audio_Yasi3",
	_2_pattern_dan14 = 	"woman/pattern_dan14",
	_2_pattern_dan10 = 	"woman/pattern_dan10",
	_2_pattern_dan11 = 	"woman/pattern_dan11",
	_2_pattern_dan12 = 	"woman/pattern_dan12",
	_2_pattern_dan13 = 	"woman/pattern_dan13",
	_2_pattern_dan16 = 	"woman/pattern_dan16",
	_2_pattern_dan15 = 	"woman/pattern_dan15",
	_2_pattern_dan17 = 	"woman/pattern_dan17",
	_2_pattern_dan3 = 	"woman/pattern_dan3",
	_2_pattern_dan4 = 	"woman/pattern_dan4",
	_2_pattern_dan5 = 	"woman/pattern_dan5",
	_2_pattern_dan6 = 	"woman/pattern_dan6",
	_2_pattern_dan7 = 	"woman/pattern_dan7",
	_2_pattern_dan8 = 	"woman/pattern_dan8",
	_2_pattern_dan9 = 	"woman/pattern_dan9",
	_2_pattern_dui14 = 	"woman/pattern_dui14",
	_2_pattern_dui10 = 	"woman/pattern_dui10",
	_2_pattern_dui11 = 	"woman/pattern_dui11",
	_2_pattern_dui12 = 	"woman/pattern_dui12",
	_2_pattern_dui13 = 	"woman/pattern_dui13",
	_2_pattern_dui15 = 	"woman/pattern_dui15",
	_2_pattern_dui16 = 	"woman/pattern_dui16",
	_2_pattern_dui17 = 	"woman/pattern_dui17",
	_2_pattern_dui3 = 	"woman/pattern_dui3",
	_2_pattern_dui4 = 	"woman/pattern_dui4",
	_2_pattern_dui5 = 	"woman/pattern_dui5",
	_2_pattern_dui6 = 	"woman/pattern_dui6",
	_2_pattern_dui7 = 	"woman/pattern_dui7",
	_2_pattern_dui8 = 	"woman/pattern_dui8",
	_2_pattern_dui9 = 	"woman/pattern_dui9",
	_2_remain1 = 	"woman/remain1",
	_2_remain2 = 	"woman/remain2",
	_2_pattern3 = 	"woman/pattern3",
	_2_pattern4 = 	"woman/pattern4",
	_2_pattern5 = 	"woman/pattern5",
	_2_pattern6 = 	"woman/pattern6",
	_2_pattern7 = 	"woman/pattern7",
	_2_pattern8 = 	"woman/pattern8",
	_2_pattern9 = 	"woman/pattern9",
	_2_pattern10 = 	"woman/pattern10",
	_2_pattern11 = 	"woman/pattern11",
	_2_pattern12 = 	"woman/pattern12",
	_2_pattern13 = 	"woman/pattern13",
	_2_pattern14 = 	"woman/pattern11",
	_2_pattern15 = 	"woman/pattern11",
	_2_pattern17 = 	"woman/pattern17",
	_2_pattern18 = 	"woman/pattern18",
	_2_pattern19 = 	"woman/pattern19",
}

export enum AudioConfig {
	Audio_You_Lose = 	"common/Audio_You_Lose",
	Audio_You_Win = 	"common/Audio_You_Win",
	Audio_Card_Click = 	"common/Audio_Card_Click",
	music_Audio_Game_Back = "Audio_Game_Back",
	music_Audio_Game_Back_Fierce = "Audio_Game_Back_Fierce",

	Audio_chupai = "common/chupai",
	Audio_feiji = "common/feiji",
	Audio_huojian = "common/huojian",
	Audio_liandui = "common/liandui",
	Audio_shunzi = "common/shunzi",
	Audio_time = "common/time",
	Audio_zhadan = "common/zhadan",
	Audio_Deal_Card = 	"common/Audio_Deal_Card",
	
	Audio_Chat_String1 = 	"?Audio_Chat_String1",
	Audio_Chat_String10 = 	"?Audio_Chat_String10",
	Audio_Chat_String2 = 	"?Audio_Chat_String2",
	Audio_Chat_String3 = 	"?Audio_Chat_String3",
	Audio_Chat_String4 = 	"?Audio_Chat_String4",
	Audio_Chat_String5 = 	"?Audio_Chat_String5",
	Audio_Chat_String6 = 	"?Audio_Chat_String6",
	Audio_Chat_String7 = 	"?Audio_Chat_String7",
	Audio_Chat_String8 = 	"?Audio_Chat_String8",
	Audio_Chat_String9 = 	"?Audio_Chat_String9",
	buyao = 	"?buyao",
	jiaofen0 = 	"?jiaofen0",
	jiaofen1 = 	"?jiaofen1",
	jiaofen2 = 	"?jiaofen2",
	jiaofen3 = 	"?jiaofen3",
	
	opcode0 = 	"?opcode0",
	opcode1 = 	"?opcode1",
	opcode2 = 	"?opcode2",
	opcode3 = 	"?opcode3",
	opcode4 = 	"?opcode4",
	opcode5 = 	"?opcode5",
	opcode6 = 	"?opcode6",

	Audio_Pass1 = 	"?Audio_Pass1",
	Audio_Pass2 = 	"?Audio_Pass2",
	Audio_Pass3 = 	"?Audio_Pass3",
	Audio_Spring = 	"?Audio_Spring",
	Audio_Pressing1 = 	"?Audio_Yasi1",
	Audio_Pressing2 = 	"?Audio_Yasi2",
	Audio_Pressing3 = 	"?Audio_Yasi3",
	pattern_dan17 = 	"?pattern_dan17",
	pattern_dan10 = 	"?pattern_dan10",
	pattern_dan11 = 	"?pattern_dan11",
	pattern_dan12 = 	"?pattern_dan12",
	pattern_dan13 = 	"?pattern_dan13",
	pattern_dan14 = 	"?pattern_dan14",
	pattern_dan15 = 	"?pattern_dan15",
	pattern_dan16 = 	"?pattern_dan16",
	pattern_dan3 = 	"?pattern_dan3",
	pattern_dan4 = 	"?pattern_dan4",
	pattern_dan5 = 	"?pattern_dan5",
	pattern_dan6 = 	"?pattern_dan6",
	pattern_dan7 = 	"?pattern_dan7",
	pattern_dan8 = 	"?pattern_dan8",
	pattern_dan9 = 	"?pattern_dan9",
	pattern_dui17 = 	"?pattern_dui17",
	pattern_dui10 = 	"?pattern_dui10",
	pattern_dui11 = 	"?pattern_dui11",
	pattern_dui12 = 	"?pattern_dui12",
	pattern_dui13 = 	"?pattern_dui13",
	pattern_dui14 = 	"?pattern_dui14",
	pattern_dui15 = 	"?pattern_dui15",
	pattern_dui16 = 	"?pattern_dui16",
	pattern_dui3 = 	"?pattern_dui3",
	pattern_dui4 = 	"?pattern_dui4",
	pattern_dui5 = 	"?pattern_dui5",
	pattern_dui6 = 	"?pattern_dui6",
	pattern_dui7 = 	"?pattern_dui7",
	pattern_dui8 = 	"?pattern_dui8",
	pattern_dui9 = 	"?pattern_dui9",
	remain1 = 	"?remain1",
	remain2 = 	"?remain2",

	pattern3 = 	"?pattern3",
	pattern4 = 	"?pattern4",
	pattern5 = 	"?pattern5",
	pattern6 = 	"?pattern6",
	pattern7 = 	"?pattern7",
	pattern8 = 	"?pattern8",
	pattern9 = 	"?pattern9",
	pattern10 = 	"?pattern10",
	pattern11 = 	"?pattern11",
	pattern12 = 	"?pattern12",
	pattern13 = 	"?pattern13",
	pattern14 = 	"?pattern11",
	pattern15 = 	"?pattern11",
	pattern16 = 	"?pattern17",
	pattern17 = 	"?pattern17",
	pattern18 = 	"?pattern18",
	pattern19 = 	"?pattern19",
	pattern22 = 	"?pattern13",
	pattern23 = 	"?pattern11",
}

export class AudioUtil {
        
    static getAudioPath(audioName: string, sex: number = 1): string {
		if(!audioName) {
			console.error(`audioName is ${audioName}`);
			return;
		}
        let pathStr = "pdk@res/audio/effect/";
        if (audioName.startsWith("?")) {
            if (sex != 1 && sex !=2) {
                console.log("==性别不对==", sex);
                sex = 1;
            }
            audioName = Meta[audioName.replace("?", `_${sex}_`)];
        }
        pathStr = pathStr.concat(audioName);
        console.log("==getAudioPath==", audioName, pathStr);
        return pathStr;
    }
	    
    static getMusicPath(musicName: string): string {
        return `pdk@res/audio/music/${musicName}`;
    }
}